Repository MoRaad97/Catalog-of-my-things-Ruby-group-capstone, pull requests merged in 2022-09, with the labels that each got.

#14 Setup the Environment.
  .github/workflows/linters.yml
  .rubocop.yml
  README.md
  app_screenshot.png
  gemfile
  gemfile.lock
Labels: good first issue

#19 Create the item class
  classes/item.rb
Labels: enhancement

#20 Write the Label Class
  classes/label.rb
Labels: enhancement

#21 Add Book & MusicAlbum Classes
  classes/book.rb
  classes/music_album.rb
Labels: enhancement

#23 Add genera source classes
  classes/genre.rb
  classes/source.rb
Labels: enhancement

#25 Add Classes
  classes/author.rb
  classes/book.rb
  classes/game.rb
  classes/genre.rb
  classes/item.rb
  classes/label.rb
  classes/movie.rb
  classes/music_album.rb
  classes/source.rb
Labels: documentation, enhancement

#26 Test 3
  classes/book.rb
  classes/music_album.rb
  helper.rb
  spec/book_spec.rb
  spec/genre_spec.rb
  spec/music_album_spec.rb
  spec/source_spec.rb
Labels: Test

#27 Test 2
  classes/music_album.rb
  helper.rb
  spec/book_spec.rb
  spec/genre_spec.rb
  spec/item_spec.rb
  spec/label_spec.rb
  spec/music_album_spec.rb
  spec/source_spec.rb
Labels: Test

#29 Unit Test
  classes/book.rb
  classes/game.rb
  classes/movie.rb
  classes/music_album.rb
  helper.rb
  spec/author_spec.rb
  spec/book_spec.rb
  spec/game_spec.rb
  spec/genre_spec.rb
  spec/item_spec.rb
  spec/label_spec.rb
  spec/movie_spec.rb
  spec/music_album_spec.rb
  spec/source_spec.rb
Labels: Test

#30 UI 1
  app.rb
  data/book.json
  data/genre.json
  data/music_album.json
  data/source.json
  helper.rb
  modules/book_handle.rb
  modules/music_album_handle.rb
  modules/reading_data.rb
Labels: enhancement
